project_id = "qemtvnwemcpzhvbwjbsk"

[functions.sync-linkedin-feed]
verify_jwt = false


[functions.publish-to-linkedin]
verify_jwt = true

[functions.publish-to-instagram]
verify_jwt = true

[functions.test-function]
verify_jwt = false

[functions.linkedin-oauth]
verify_jwt = false

[functions.linkedin-integration]
verify_jwt = false