project_id = "qemtvnwemcpzhvbwjbsk"


[functions.publish-to-linkedin]
verify_jwt = true

[functions.publish-to-instagram]
verify_jwt = true

[functions.test-function]
verify_jwt = false

[functions.linkedin-oauth]
verify_jwt = false