project_id = "qemtvnwemcpzhvbwjbsk"

[auth]
enabled = true
site_url = "https://polrydian.com"
additional_redirect_urls = ["https://d85f6385-6c6d-437f-978b-9196bd33e526.lovableproject.com"]

[functions.sync-linkedin-feed]
verify_jwt = true

[functions.share-to-linkedin]
verify_jwt = true

[functions.linkedin-oauth]
verify_jwt = true

[functions.publish-to-instagram]
verify_jwt = true

[functions.fetch-economic-insights]
verify_jwt = true

[functions.token-refresh-cron]
verify_jwt = false

[functions.integration-health-monitor]
verify_jwt = true

[functions.test-function]
verify_jwt = true

[functions.multi-source-economic-data]
verify_jwt = true

[functions.fred-api-integration]
verify_jwt = true

[functions.enhanced-data-collection]
verify_jwt = true

[functions.research-link-generator]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-rss]
verify_jwt = false

[functions.secure-contact-form]
verify_jwt = false

[functions.security-audit]
verify_jwt = false