import { useEffect } from 'react';

export default function RSS() {
  useEffect(() => {
    // Redirect to the live RSS feed generated by Supabase Edge Function
    window.location.href = 'https://qemtvnwemcpzhvbwjbsk.supabase.co/functions/v1/generate-rss';
  }, []);

  return (
    <div className="min-h-screen bg-background flex items-center justify-center">
      <div className="text-center">
        <p className="text-muted-foreground">Redirecting to RSS feed...</p>
      </div>
    </div>
  );
}