import { useEffect } from 'react';

export default function Sitemap() {
  useEffect(() => {
    // Redirect to the live sitemap generated by Supabase Edge Function
    window.location.href = 'https://qemtvnwemcpzhvbwjbsk.supabase.co/functions/v1/generate-sitemap';
  }, []);

  return (
    <div className="min-h-screen bg-background flex items-center justify-center">
      <div className="text-center">
        <p className="text-muted-foreground">Redirecting to sitemap...</p>
      </div>
    </div>
  );
}