// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qemtvnwemcpzhvbwjbsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlbXR2bndlbWNwemh2YndqYnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTE2ODQsImV4cCI6MjA2ODIyNzY4NH0.9UikTq1ajnfhthHxx_03zRk_3G3G_Bgky_w21wMXzLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});