name: Semgrep SAST
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "dev" ]
permissions:
  contents: read
  security-events: write
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: "1"
